=== mamedev/mame/trunk/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT software (description, year?, publisher, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea databits (8|16|32|64) "8">
				<!ATTLIST dataarea endian (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== mamedev/mame/hash/ngp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="ngp" description="SNK Neo Geo Pocket cartridges">

<!-- Undumped:
NEOP00060 Dokodemo Mahjong
-->

	<!-- Developer: SNK -->
	<software name="bstars">
		<description>Pocket Sports Series - Baseball Stars (Europe, Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00070" />
		<info name="release" value="19981126 (JPN)" />
		<info name="alt_title" value="ポケットスポーツシリーズ ベースボール スターズ" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="baseball stars (japan, europe) (en,ja).bin" size="1048576" crc="4781ae84" sha1="8ece00f21ae49ed4777a9c990b2782465ef95380" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="kof_mlon">
		<description>King of Fighters R-1 &amp; Melon-chan no Seichou Nikki (Japan, prototype)</description>
		<year>199?</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00130" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="2097152">
				<rom name="king of fighters r-1 &amp; melon-chan no seichou nikki (japan) (beta).bin" size="2097152" crc="2660bfc4" sha1="a02d1b1113dbeac895832f1501029e40d9aab493" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: SNK -->
	<software name="kofr1">
		<description>Pocket Fighting Series - King of Fighters R-1 (Europe, Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00010" />
		<info name="release" value="19981028 (JPN)" />
		<info name="alt_title" value="ポケット格闘シリーズ キング・オブ・ファイターズ R-1" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="2097152">
				<rom name="king of fighters r-1 (japan, europe) (en,ja).bin" size="2097152" crc="dceb7e11" sha1="4a7adbcccb05b6047a38bb861523cbae7d956bfa" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: ADK -->
	<software name="melonchn">
		<description>Melon-chan no Seichou Nikki (Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00040" />
		<info name="release" value="19981028" />
		<info name="alt_title" value="めろんちゃんの成長日記" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="melon-chan no seichou nikki (japan).bin" size="1048576" crc="cb42cfa4" sha1="2dbf9c40ab0167ff172f10354d4674e5e6c901d5" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: Dyna -->
	<software name="neocher">
	<!-- NGPC, rated "Over 18" -->
		<description>Pocket Casino Series - Neo Cherry Master (Europe, Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00140" />
		<info name="release" value="19981225 (JPN)" />
		<info name="alt_title" value="ポケットカジノシリーズ ネオ・チェリーマスター" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="neo cherry master - real casino series (japan, europe) (en,ja).bin" size="1048576" crc="5c067579" sha1="c171d8d22d667d713bfc73c2b1c04bc77aacbb5c" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: SNK -->
	<software name="neocup98">
		<description>Pocket Sports Series - Neo Geo Cup '98 (Europe, Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00020" />
		<info name="release" value="19981028 (JPN)" />
		<info name="alt_title" value="ポケットスポーツシリーズ ネオジオカップ'98" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="neo geo cup '98 (japan, europe) (en,ja).bin" size="1048576" crc="33add5bd" sha1="445743119c65a6765a0bdc849a12e9038192840c" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: Yumekobo -->
	<software name="ptennis">
		<description>Pocket Sports Series - Pocket Tennis (Europe, Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00090" />
		<info name="release" value="19981028 (JPN)" />
		<info name="alt_title" value="ポケットスポーツシリーズ ポケットテニス" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="0x80000">
				<!-- bad dump with crc 89410850 and 0x00 padding instead of 0xff padding also exists -->
				<rom name="pocket tennis - pocket sports series (japan, europe) (en,ja).bin" size="0x80000" crc="4b1eed05" sha1="67826f4c8e488938f7e1b26e331f79ebf0aa2565" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: SNK -->
	<software name="samsho">
	<!-- NGPC -->
		<description>Pocket Fighting Series - Samurai Spirit! (Japan) ~ Samurai Shodown! (Europe)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00080" />
		<info name="release" value="19981225 (JPN)" />
		<info name="alt_title" value="ポケット格闘シリーズ サムライスピリッツ!" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="2097152">
				<rom name="samurai shodown - pocket fighting series (japan, europe) (en,ja).bin" size="2097152" crc="32e4696a" sha1="2c6adfa69e7aeada7d4198b373436eee35b70d01" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: ADK -->
	<software name="shougi">
		<description>Shougi no Tatsujin (Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00050" />
		<info name="release" value="19981120" />
		<info name="alt_title" value="将棋の達人" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="524288">
				<rom name="shougi no tatsujin (japan).bin" size="524288" crc="f34d0c9b" sha1="ab0c33236f72d2b317d91d034756b56cfca1b0b4" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: Yumekobo -->
	<software name="tsunapn">
		<description>Renketsu Puzzle Tsunagete Pon! (Japan)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00120" />
		<info name="release" value="19981028" />
		<info name="alt_title" value="連結パズル つなげてポンッ!" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="524288">
				<rom name="renketsu puzzle tsunagete pon (japan).bin" size="524288" crc="ce09f534" sha1="cbe53b08d03ef684c08fc6ee28fca168a3d091a7" offset="000000" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/abc80_cass.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="abc80_cass" description="Luxor ABC 80 cassettes">

	<!-- https://www.youtube.com/watch?v=5IVFEVL4oAg -->
	<software name="abcdemo">
		<description>ABCDemo</description>
		<year>2015</year>
		<publisher>Genesis Project</publisher>
		<info name="usage" value="RUN CAS:" />

		<part name="cass1" interface="abc80_cass">
			<dataarea name="cass" size="10793090">
				<rom name="genesisproject_abcdemo.wav" size="10793090" crc="7642349f" sha1="a0a808e9c9c5f3ca162ef22869600e1c735846c2"/>
			</dataarea>
		</part>
	</software>

	<software name="abcstack">
		<description>ABCStacker</description>
		<year>2016</year>
		<publisher>Andreas Gustafsson</publisher>
		<info name="usage" value="RUN CAS:" />

		<part name="cass1" interface="abc80_cass">
			<dataarea name="cass" size="755244">
				<rom name="abcstacker.wav" size="755244" crc="6fdc6043" sha1="2a8290f260e94bb5904733255aa0e0188a2168b8"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/p2k_cass.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<softwarelist name="p2k_cass" description="Philips P2000 cassettes">
	<software name="3ddool2">
		<description>3D Doolhof 2 (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="11520">
				<rom name="3d doolhof 2 (19xx)(-)(nl).cas" size="11520" crc="f3edc8b1" sha1="edc1f115be71029e91c0b617be8f35df1f921b81" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="brickwal">
		<description>Brick-Wall (Ned, v3.0)</description>
		<year>1982</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="17920">
				<rom name="brick-wall v3.0 (1982)(-)(nl).cas" size="17920" crc="b3d7ff52" sha1="ac0907cd223bd434262cfedb39a2b94ce4557820" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="componis">
		<description>Componist (Ned)</description>
		<year>1984</year>
		<publisher>A. Dobber</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="12800">
				<rom name="componist (1984)(a. dobber)(nl).cas" size="12800" crc="aadd88b3" sha1="72ba868d38b822e011b5145c95f0509529fa275e" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="elevator">
		<description>Elevator Humpie (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="7680">
				<rom name="elevator humpie (19xx)(-)(nl).cas" size="7680" crc="dd95644d" sha1="3dc8257bff5513b66e6b6566c7f8343817927d37" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="errsoft">
		<description>Ghost Hunter &amp; Racen (v2.0) (Ned)</description>
		<year>198?</year>
		<publisher>Errorsoft</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="25600">
				<rom name="ghost hunter (19xx)(errorsoft)(nl) &amp; racen v2.0 (19xx)(errorsoft)(nl).cas" size="25600" crc="4ddf2e30" sha1="c6421914a709ebc7a5ab920e76b1c076b35c3f89" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="kleuren">
		<description>Kleurendemonstratie (v3.9, Bad?)</description>
		<year>1983</year>
		<publisher>Klaas H.J. Roberts</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="15360">
				<rom name="kleurendemonstratie v3.9 (1983)(klaas h.j. roberts)[b].cas" size="15360" crc="45dd7e0f" sha1="f75ea81dd6c355c4ed0fd7a1b32374a5f2c00661" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="lazybug">
		<description>Lazy Bug (Ned, v6.0, Bad?)</description>
		<year>1985</year>
		<publisher>Double Brain</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="12800">
				<rom name="lazy bug v6.0 (1985)(double brain)(nl)[b].cas" size="12800" crc="8f322af1" sha1="d7b06d8c870098197efe1de079b30f16b03070a4" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="machoman">
		<description>Macho Man (v2.1, Bad?)</description>
		<year>1986</year>
		<publisher>J. Nieuwenhuizen</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="11520">
				<rom name="macho man v2.1 (1986)(j. nieuwenhuizen)[b].cas" size="11520" crc="1b2646fe" sha1="373430fa7e0a08dcd3483681c22d3c57c78bebe6" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="mkong">
		<description>Monkey Kong - Deel II (Ned, v1.0)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="11520">
				<rom name="monkey kong v1.0 deel ii (19xx)(-)(nl).cas" size="11520" crc="9a919e58" sha1="b7ae2607d6399d8fbb487dd61c7b382c10c2d1c6" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="snakey">
		<description>Snakeygame</description>
		<year>198?</year>
		<publisher>NOS - Thomas Hofmeister</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="7680">
				<rom name="snakeygame (19xx)(nos - thomas hofmeister).cas" size="7680" crc="3288dca2" sha1="2f6f0c55cb4dbd9f5dcb4ec8af41c8b3db0aaff8" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spaceatk">
		<description>Space Attack (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="14080">
				<rom name="space attack (19xx)(-)(nl).cas" size="14080" crc="39a8b855" sha1="2064084fb9dbc8afbee53f311bede4b252c3bd82" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spacef2">
		<description>Space Fight II - Fraxxon (v1.0)</description>
		<year>1985</year>
		<publisher>LBK Production</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="30720">
				<rom name="space fight ii - fraxxon v1.0 (1985)(lbk production).cas" size="30720" crc="e5e974bf" sha1="63f4478fa2b79a38a631b65559a3da36e4ce363f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spacef">
		<description>Space Fight (Ned, v3.0, Bad?)</description>
		<year>1984</year>
		<publisher>L.B. Kruijswijk</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="14080">
				<rom name="space fight v3.0 (1984)(l.b. kruijswijk)(nl)[b].cas" size="14080" crc="59091f51" sha1="7cf241b9debe8cae556a6412eee729fe3b846a4f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spacem">
		<description>Space Mission (Ned)</description>
		<year>1984</year>
		<publisher>P. v. H.</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="23040">
				<rom name="space mission (1984)(p. v. h.)(nl).cas" size="23040" crc="64907d33" sha1="5cb916c47f058efa221e3f8f2cfd3c91509a6015" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spellpal">
		<description>Speelpaleis (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="15360">
				<rom name="speelpaleis (19xx)(-)(nl).cas" size="15360" crc="b46b537e" sha1="366abaaa4089d5603d63ea56ca89b01e7031c3e6" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="startrek">
		<description>Startrek (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="17920">
				<rom name="startrek (19xx)(-)(nl).cas" size="17920" crc="8480161f" sha1="7caf5c6f3d4dd3afdf2bb300b3253bc7a8b87351" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="vlucht">
		<description>Vlucht Simulator (Ned, Bad?)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="38400">
				<rom name="vlucht simulator (19xx)(-)(nl)[b].cas" size="38400" crc="74958e0a" sha1="9d1e83998549356ddc6dc2fcbc767462c82da833" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/photo_cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

https://redump.info/discs/system/photo-cd/
-->
<softwarelist name="photo_cd" description="Kodak Photo CD images (Beige Book)">

	<software name="flowers" supported="partial">
		<!--
		Origin: TOSEC
		<rom name="Flowers of Robert Mapplethorpe, The (1992)(Philips)(US)(Track 1 of 2)[!][Photo CD].iso" size="511030800" crc="fbf3915f" md5="22ae24fd51d368f534b3963aed4a8350"/>
		<rom name="Flowers of Robert Mapplethorpe, The (1992)(Philips)(US)(Track 2 of 2)[!][Photo CD].wav" size="218030444" crc="73b4776b" md5="ac291bb92f9033e9a90cb8572de02a6c"/>
		<rom name="Flowers of Robert Mapplethorpe, The (1992)(Philips)(US)[!][Photo CD].cue" size="333" crc="5d4e0813" md5="7d75fbaa2960289a5f4a17e591db0b76"/>
		-->
		<description>The Flowers of Robert Mapplethorpe (USA)</description>
		<year>1992</year>
		<publisher>Philips Interactive Media</publisher>
		<notes><![CDATA[
https://www.theworldofcdi.com/cd-i_encyclopedia/flowers-of-robert-mapplethorpe/
3do_*: either purges the disc or hangs with a blue screen, incompatible?
]]></notes>
		<info name="barcode" value="7 31069 02232 9"/>
		<info name="serial" value="310690223-2"/>
		<!-- PCEC: PP0223 GA -->
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="flowers of robert mapplethorpe, the (1992)(philips)(us)[photo cd]" sha1="e66a82313a0894eff7d93803febb645c7fd67f07"/>
			</diskarea>
		</part>
	</software>

	<software name="howphoto" supported="partial">
		<!--
		Origin: TOSEC
		<rom name="How to Photograph Nature (1993)(Philips)(US)(Track 1 of 2)[!][CD-i-Photo CD].iso" size="490392000" crc="e3c64107" md5="c9b23be5e796b517f29b77a358f7deaf"/>
		<rom name="How to Photograph Nature (1993)(Philips)(US)(Track 2 of 2)[!][CD-i-Photo CD].wav" size="230202044" crc="c92dbd5b" md5="d816d1ef2c27d4f10be7e0ba7b8f274e"/>
		<rom name="How to Photograph Nature (1993)(Philips)(US)[!][CD-i-Photo CD].cue" size="321" crc="7a10ddfa" md5="59c7d8e28bb242bf0c0c6a33491b03fc"/>
		-->
		<description>How to Photograph Nature (USA)</description>
		<year>1993</year>
		<publisher>Philips Interactive Media</publisher>
		<notes><![CDATA[
https://www.theworldofcdi.com/cd-i_encyclopedia/how-to-photograph-nature/
3do_*: either purges the disc or hangs with a blue screen, incompatible?
]]></notes>
		<info name="barcode" value="73106902248"/>
		<info name="serial" value="310690224-2"/>
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="how to photograph nature (1993)(philips)(us)[cd-i-photo cd]" sha1="5a0338596cec6feef16283ba7c3aa30066d48a77"/>
			</diskarea>
		</part>
	</software>

	<software name="pcd1904" supported="partial">
		<!--
		Origin: Foxhack
		<rom name="PCD1904 (Track 1).bin" size="818496" crc="1d037f6d" md5="05dde46197ea63a14510717960e414fd" sha1="0a805e88a5f40e5fd6ba8a579cb6ca0cf379ed05" />
		<rom name="PCD1904 (Track 2).bin" size="100018800" crc="24233b6d" md5="24444ff73512426f74e2fc0505bf0df6" sha1="34c8dd58666d502ede55d632e643bd121426a1a0" />
		<rom name="PCD1904 (Track 3).bin" size="16581600" crc="b779625b" md5="fc057c2568599b68bd3a657e3688ef85" sha1="b3c4ad5df7568b0a891d192bc49f673e352fd243" />
		<rom name="PCD1904 (Track 4).bin" size="4762800" crc="88c2e4e9" md5="cd6402f0b46c83996d24826a03186c3c" sha1="5690073a9162bf31123e07f6fdd8e1ddcc8077d4" />
		<rom name="PCD1904 (Track 5).bin" size="132300000" crc="c4a7ee90" md5="3c4731edeffded203ab96c184edd84d1" sha1="723f14cad145fb8dc197d2066ae77fb09a775d93" />
		<rom name="PCD1904 (Track 6).bin" size="38631600" crc="099b3382" md5="2bc8816b0d2194801e6a98e756067613" sha1="79712b1aa0a0b5b4901d3ed91cde25ac871b029d" />
		<rom name="PCD1904 (Track 7).bin" size="26460000" crc="7b76c4b6" md5="4586c3b510abf2dee4ac532a2ad6bf86" sha1="3407398b97cae5d5af4121cd2759c85f1dcf4b49" />
		<rom name="PCD1904 (Track 8).bin" size="26283600" crc="825108c2" md5="c118c88266b337ebbd5df15bca71a8a5" sha1="24d9e26729e780891a598657fabf11a41708f67a" />
		<rom name="PCD1904 (Track 9).bin" size="41207040" crc="823fb562" md5="f2abea76d3e4d823c2356232ad60d39c" sha1="ce794bbf1b299107133cb8797342e44868d90b6c" />

		Note: This is a Windows ISO9660-formatted CD that included Photo CD on CD-Interactive, Version 3.1 (April 14, 1993). This disc also works under Windows
		3.1, and includes demo software for that platform.

		-->
		<description>The Photo CD Book Companion CD-ROM</description>
		<year>1994</year>
		<publisher>Abacus</publisher>
		<notes><![CDATA[
3do_fz1*: purged at startup, incompatible?
ibmpc win95: verify compatibility (conceals mouse cursor on Win 3.1 style windowing)
]]></notes>
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="pcd1904" sha1="19c7875a0329b2a75b3c0c05fa646536473e8c7d"/>
			</diskarea>
		</part>
	</software>

	<software name="photocdd" supported="partial">
		<!--
		Origin: TOSEC
		<rom name="Photo CD Demo Disc v3.2 (1995)(Philips)(EU)[1995-11].iso" size="297281040" crc="4090c3ad" md5="ee6557e858a6b789bb622c34e429c54e"/>
		<rom name="Photo CD Demo Disc v3.2 (1995)(Philips)(EU)[1995-11].cue" size="141" crc="16767025" md5="e0be2e958b118049ec1d582e24f4332c"/>
		-->
		<description>Photo CD Demo Disc (Europe, v3.2)</description>
		<year>1995</year>
		<publisher>Philips Interactive Media</publisher>
		<notes><![CDATA[
https://www.theworldofcdi.com/cd-i_encyclopedia/photo-cd-demo-disc-3-2/
3do_fz1*: purged at startup, incompatible?
pcfx: background strip of garbage on thumbnails screen (verify)
]]></notes>
		<info name="release" value="199511xx"/>
		<!-- serial: 902272 / 998014 -->
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="photo cd demo disc v3.2 (1995)(philips)(eu)[1995-11]" sha1="d32fb0741e06f247c6f2b7e49c66ea284a0d5caf"/>
			</diskarea>
		</part>
	</software>

	<software name="photocddo" cloneof="photocdd" supported="partial">
		<!--
		Origin: TOSEC
		<rom name="Photo CD Demo Disc v3.0 (1993)(Philips)(EU)[1993-03].iso" size="463108800" crc="58fce69a" md5="c5cb66dff16c1ec69bc118a394eab777"/>
		<rom name="Photo CD Demo Disc v3.0 (1993)(Philips)(EU)[1993-03].cue" size="141" crc="5f1b92d2" md5="9f82863685d80426ce9e0eb37fe4d703"/>
		-->
		<description>Photo CD Demo Disc (Europe, v3.0)</description>
		<year>1993</year>
		<publisher>Philips Interactive Media</publisher>
		<notes><![CDATA[
https://www.theworldofcdi.com/cd-i_encyclopedia/photo-cd-demo-disc-3-0/
3do_fz1*: purged at startup, incompatible?
]]></notes>
		<info name="release" value="199303xx"/>
		<info name="serial" value="819.0007"/>
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="photo cd demo disc v3.0 (1993)(philips)(eu)[1993-03]" sha1="bd46faaebe1725eb345de81dd912187b74b4dea8"/>
			</diskarea>
		</part>
	</software>

	<software name="schonste" supported="no">
		<!--
		Origin: TOSEC
		<rom name="Schonsten Hotels der Welt, Die - von Burba Holiday (1992)(Philips)(DE)[!][Photo CD].iso" size="117835200" crc="be3eabc9" md5="e1bea9ed5369040db3e669409ce362da"/>
		<rom name="Schonsten Hotels der Welt, Die - von Burba Holiday (1992)(Philips)(DE)[!][Photo CD].cue" size="172" crc="cbdde2d5" md5="e0029a07753cb512891111325f0c4536"/>
		-->
		<description>Die Schonsten Hotels der Welt: von Burba Holiday (Germany)</description>
		<year>1992</year>
		<publisher>Philips Interactive Media</publisher>
		<notes><![CDATA[
https://www.theworldofcdi.com/cd-i_encyclopedia/die-schonsten-hotels-der-welt/
3do_fz1*: purged at startup, incompatible?
pcfx: hangs at 4th photo of 1st hotel package (that shows as rotated in CD-i) (verify)
cdimono1: doesn't show main menu as pcfx (last photo, verify), thumbnail 19 doesn't decode properly (bad dump?)
]]></notes>
		<info name="serial" value="8130060"/>
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="schonsten hotels der welt, die - von burba holiday (1992)(philips)(de)[photo cd]" sha1="f233fa4abf5b60a363f1e664a3f5688193e05a78" status="baddump" />
			</diskarea>
		</part>
	</software>

	<software name="toilhana" supported="partial">
		<!-- https://redump.info/disc/103991/ -->
		<description>Toilet no Hanako-san (Japan)</description>
		<year>1995</year>
		<publisher>Times In</publisher>
		<notes><![CDATA[
3do_fz*: DSPP punts with a loud bang once its supposed to playback any voice
]]></notes>
		<info name="alt_title" value="トイレの花子さん" />
		<info name="serial" value="PCD0924" />
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="toilet_no_hanako-san_(japan)" sha1="bb35be781dcf134f1225df7352f8bcac1ab11629"/>
			</diskarea>
		</part>
	</software>

	<software name="winsenna" supported="partial">
		<!-- https://redump.info/disc/103998/ -->
		<description>Winning Run: Ayrton Senna: 20-nen no Kiseki (Japan)</description>
		<year>1995</year>
		<publisher>Kasakura Shuppan</publisher>
		<notes><![CDATA[
3do_fz*: Doesn't playback any voice (verify)
]]></notes>
		<info name="alt_title" value="ＷＩＮＮＩＮＧ ＲＵＮ アイルトン・セナ ２０年の軌跡" />
		<info name="barcode" value="T4934878151235" />
		<info name="serial" value="PCD0806" />
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="winning_run_-_ayrton_senna_-_20-nen_no_kiseki_(japan)" sha1="0bf605a8e5713f5802f827424507f53e65f586e7"/>
			</diskarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/spectrum_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<!-- ZX Spectrum Disc images
    for +3 machines etc.
-->


<softwarelist name="spectrum_flop" description="ZX Spectrum Disc Images">
	
	<software name="pacmania" >
		<description>Pac-Mania (Europe / Australia)</description>
		<year>1988</year>
		<publisher>Namco / Grandslam</publisher>
		<part name="flop1" interface="floppy_3">
			<dataarea name="flop" size="195328">
				<rom name="pac-mania.dsk" size="195328" crc="88f5506b" sha1="827c95935dd3a1dd919989fc6d7a0efa4e5aebc1" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/ibm5150_demos.xml
<?xml version="1.0" ?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="ibm5150_demos" description="IBM PC floppy disk (demoscene)">

	<software name="8088mph" supported="no">
		<description>8088 MPH (Final Version)</description>
		<year>2015</year>
		<publisher>Hornet + CRTC + DESiRE</publisher>
		<notes><![CDATA[
Prints "Metric cycle count of 1127 deviates 33%" with ibm5160
Various GFX glitches, cfr. https://youtu.be/hNRO7lno_DM for side by side test
Hangs at credits screen
]]></notes>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size = "368640">
				<rom name="8088mph final.360" size="368640" crc="a30504e8" sha1="5f637b83dca774b7104fed0d20195dd769e0838b"/>
			</dataarea>
		</part>
	</software>

	<software name="8088mphp" cloneof="8088mph" supported="no">
		<description>8088 MPH (Revision 2015 Party version)</description>
		<year>2015</year>
		<publisher>Hornet + CRTC + DESiRE</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size = "368640">
				<rom name="8088mph.360" size="368640" crc="4f5f4871" sha1="b7f61ad133edf7e80d2ccd0bc7767baf0b13f34d"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/cbm_sd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="cbm_sd" description="Commodore SD card images">

	<software name="sd2iec">
		<description>SD2IEC</description>
		<year>2013</year>
		<publisher>NBLA000</publisher>
		<sharedfeat name="iec8_default" value="sd2iec"/>

		<!-- 16GB FAT32 disk with CBM-FileBrowser v1.6 -->
		<part name="card" interface="sdcard">
			<diskarea name="harddriv">
				<disk name="sd2iec" sha1="258cd2ae923fb6e054f9179b5ac94d394a1f5cfd" writeable="yes" />
			</diskarea>
		</part>
	</software>

</softwarelist>
