=== mamedev/mame/trunk/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT software (description, year?, publisher, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea databits (8|16|32|64) "8">
				<!ATTLIST dataarea endian (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== mamedev/mame/hash/tx0_ptp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="tx0_ptp" description="TX-0 Paper Tape Reader images">
	<!-- The "8N" compatibility tag is used for programs written or reassembled after 1960, using the revised instruction code.
	     The encoding of "64" and "8O" programs is incompatible with the tx0_8kw system. These two categories may receive separate lists in the future.
	-->

	<software name="flit">
		<description>FLIT - Flexowriter Interrogation Tape</description>
		<year>1961</year>
		<publisher>MIT</publisher>
		<info name="author" value="J. B. Dennis &amp; T. G. Stockham"/>
		<info name="usage" value="Press read in switch, then wait for loader to finish before typing commands."/>
		<sharedfeat name="compatibility" value="8N"/>
		<part name="ptp" interface="tx0_ptp">
			<feature name="blocks_used" value="13500-17777"/>
			<dataarea name="ptap" size="7163">
				<rom name="bin_flitI_8-2-61.bin" size="7163" crc="0e983392" sha1="633ceac020cc8db09d4790abf3dbc95f6e5d600d"/>
			</dataarea>
		</part>
	</software>

	<software name="flit2">
		<description>FLIT II</description>
		<year>1961</year>
		<publisher>MIT</publisher>
		<info name="usage" value="Press read in switch, then wait for loader to finish before typing commands."/>
		<sharedfeat name="compatibility" value="8N"/>
		<part name="ptp" interface="tx0_ptp">
			<feature name="blocks_used" value="13422-17777"/>
			<dataarea name="ptap" size="7339">
				<rom name="bin_flitII.bin" size="7339" crc="432dbf25" sha1="e549e008655c32809d1135f52bbe5c4c3f5767df"/>
			</dataarea>
		</part>
	</software>

	<software name="flitlp">
		<description>FLITloader Punch</description>
		<year>1960</year>
		<publisher>MIT</publisher>
		<info name="usage" value="Create file for punch device. Press read in switch, then restart after loader halts at 7777."/>
		<sharedfeat name="compatibility" value="8O"/>
		<part name="ptp" interface="tx0_ptp">
			<!-- Original binary dump contained many errors which have been patched to match the listing. -->
			<feature name="blocks_used" value="20-175, 7742-7777 (loader), 17660-17777 (FLITloader)"/>
			<dataarea name="ptap" size="931">
				<rom name="bin_flitLdrPunch.bin" size="931" crc="7888fb81" sha1="e1d79f13d21ba2b263c1d94e17c697c271f408c7" status="baddump"/>
			</dataarea>
		</part>
	</software>

	<software name="munching">
		<description>Munching Squares</description>
		<year>196?</year>
		<publisher>MIT</publisher>
		<info name="usage" value="Press read in switch, then restart after loader halts at 17777. Use TAC switches to vary display pattern."/>
		<sharedfeat name="compatibility" value="8N"/>
		<part name="ptp" interface="tx0_ptp">
			<feature name="blocks_used" value="20-52, 17756-17777"/>
			<dataarea name="ptap" size="327">
				<rom name="bin_munchingSquares.bin" size="327" crc="54afd9a3" sha1="a7fc6d62ea1cef21f1563cb8b86a5e63198af0ae"/>
			</dataarea>
		</part>
	</software>

	<software name="punchy">
		<description>Punchy</description>
		<year>195?</year>
		<publisher>MIT</publisher>
		<info name="author" value="John T. Gilmore, Jr."/>
		<info name="usage" value="Create file for punch device. Press read in switch, then restart after loader halts at 7777."/>
		<!-- For detailed usage instructions, see memorandum M-5001-1. -->
		<sharedfeat name="compatibility" value="64,8O"/>
		<part name="ptp" interface="tx0_ptp">
			<!-- Reconstructed from assembly listing dated "3 FEB" in handwriting, together with the standard tape input routine from M-5001-1.
			     This version is independent of UT-3, but does require that the aforementioned input routine remain in memory. -->
			<feature name="blocks_used" value="6547-7610, 7741-7777"/>
			<dataarea name="ptap" size="1821">
				<rom name="punchy.bin" size="1821" crc="3a0ead7e" sha1="6fb6f072251712cab2e614d1a80a626b9a27f1f2"/>
			</dataarea>
		</part>
	</software>

	<software name="ut3">
		<description>Utility Tape 3</description>
		<year>1958</year>
		<publisher>MIT</publisher>
		<info name="author" value="Charles Woodward"/>
		<info name="usage" value="Press read in switch, then wait for loader to finish before typing commands."/>
		<!-- Commands recognized: addr(ess), word, surp(ise), goto, pntv(ertical), pnth(orizontal), punc(h), inpu(t).
		     Subcommands recognized: cons(tants), inst(ructions).
		     The Trace tape optionally replaces pntv and pnth with new commands trac(e) and begi(n).
		     For detailed usage instructions, see memorandum M-5001-1. Note that the 'slash' character is |, not /. -->
		<sharedfeat name="compatibility" value="64,8O"/>
		<part name="ptp1" interface="tx0_ptp">
			<!-- Reconstructed from assembly listing dated "27 Feb 1958" in handwriting. The opcodes for 'rfa', 'rfl' and 'rfr'
			     are uncertain; it has been assumed that these are the "start PETR running" OPRs described in 6M-4789-1. -->
			<feature name="part_id" value="UT3"/>
			<feature name="blocks_used" value="5540-7611, 7622-7777"/>
			<dataarea name="ptap" size="3381">
				<rom name="ut3.bin" size="3381" crc="b287f67f" sha1="40ec0c15873dae9b139af3c6dc756268fa87f63d" status="baddump"/>
			</dataarea>
		</part>
		<part name="ptp2" interface="tx0_ptp">
			<!-- Reconstructed from undated assembly listing. -->
			<feature name="part_id" value="Trace"/>
			<feature name="blocks_used" value="6657-7160, 7316-7331"/>
			<dataarea name="ptap" size="642">
				<rom name="trace.bin" size="642" crc="b8850e4b" sha1="4345f24aeea472d5c357641d8a868e8326a015bc"/>
			</dataarea>
		</part>
	</software>

	<software name="ut3tra" cloneof="ut3">
		<description>Utility Tape 3 ('tra' modification)</description>
		<year>1959?</year>
		<publisher>MIT</publisher>
		<!-- Reconstructed from patches in appendix to UT3 assembly listing. This modification both supports and requires the new 'tra' instruction. -->
		<info name="usage" value="Press read in switch, then wait for loader to finish before typing commands."/>
		<sharedfeat name="compatibility" value="8O"/>
		<part name="ptp" interface="tx0_ptp">
			<feature name="blocks_used" value="5540-7611, 7622-7777"/>
			<dataarea name="ptap" size="3381">
				<rom name="ut3_tra.bin" size="3381" crc="a71f37a6" sha1="c60575cfe2cf0451660c846a927ad05747693ff5"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/cbm2_cart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="cbm2_cart" description="Commodore CBM-II cartridges">

	<software name="profitxt">
		<description>Profi-Text</description>
		<year>198?</year>
		<publisher>Völkner Electronic</publisher>

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="profitext.bin" size="0x2000" crc="ac622a2b" sha1="a02fcd187b7493a08379bbaef3d4296a083d30c8"/>
			</dataarea>
		</part>
	</software>

	<software name="calcres" supported="no">
		<description>Calc Result</description>
		<year>198?</year>
		<publisher>Handic Software</publisher>
		<notes><![CDATA[
Requires disk
]]></notes>
		
		<dataarea name="bank1" size="0x2000">
			<rom name="cbm610-cart1-blue-right.bin" size="0x2000" crc="61a5008b" sha1="02db07ca68631aefb69e5db41fada27486263c69"/>
		</dataarea>
	</software>

	<software name="demo1" supported="no">
		<description>Demo 1</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="cbm610-cart1-red-left.bin" size="0x2000" crc="be426f3d" sha1="da6f1099fd09165f8ee454e2e517cfc523deb8b7"/>
			</dataarea>
		</part>
	</software>

	<software name="demo2" supported="no">
		<description>Demo 2</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="cbm610-cart2-white-left.bin" size="0x2000" crc="aeb6881c" sha1="4bdabbd7d6d642f916b5a91155396c98fce591a3"/>
			</dataarea>
		</part>
	</software>

	<software name="moni610">
		<description>Moni 610</description>
		<year>1988</year>
		<publisher>Ullrich von Bassewitz</publisher>
		<info name="usage" value="SYS 16384" />

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank2" size="0x2000">
				<rom name="moni610.bin" size="0x2000" crc="43b08d1f" sha1="9c0c24907e85674348dd58e81e6da64e157e9d0f"/>
			</dataarea>
		</part>
	</software>

	<software name="vt52">
		<description>VT52 Emulator (Hungary)</description>
		<year>1986</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Press 'ESC-?' to run" />

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank2" size="0x2000">
				<rom name="vt52emu.bin" size="0x2000" crc="b3b6173a" sha1="dd4a412a1a6ce4272b02d731364dd6dc96a4570b"/>
			</dataarea>
		</part>
	</software>

	<software name="cbm2diag">
		<description>Commodore CBM 600/700 Diagnostic</description>
		<year>198?</year>
		<publisher>Commodore</publisher>
		<notes><![CDATA[
No cassette test 
]]></notes>

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="cbm2_diag_2000.bin" size="0x2000" crc="5ba26a70" sha1="c0733941e6cb00a3299713cceef3d1bbcf830236"/>
			</dataarea>
		</part>
	</software>

	<software name="cbm2diaga" cloneof="cbm2diag">
		<description>Commodore CBM 600/700 Diagnostic (alt)</description>
		<year>198?</year>
		<publisher>Commodore</publisher>

		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="324835-01.bin" size="0x2000" crc="a4808500" sha1="28c2a74a8050437aa21057ee18ddc47df26a143d"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/mikrosha_cart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="mikrosha_cart" description="Mikrosha cartridges">

	<software name="micron">
		<description>BASIC-Micron, ED.Micron, Assembler</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="cart" interface="mikrosha_cart">
			<dataarea name="rom" size="16384">
				<rom name="micron.rom" size="16384" crc="42ac7739" sha1="ca7ac6e0f38d54274db14d1dd4141722908b2d8b"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/mac_hdd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="mac_hdd" description="Apple Macintosh hard disk images">
	<software name="mac608">
		<description>System Software 6.0.8</description>
		<year>1988</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac608" sha1="0eff82806f671484ec0c91cdc95ad90aa3157885" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac700">
		<description>System Software 7.0</description>
		<year>1991</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac700" sha1="a4c7777125331339afcd47dda5adca26ff57a427" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac701">
		<description>System Software 7.0.1</description>
		<year>1991</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac701" sha1="f867db45d7543ba87ca0e762bc920fe11d2a0753" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac711">
		<description>System Software 7.1.1</description>
		<year>1993</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac711" sha1="b1625378d1ba00861a07ebe47f4b6b54c849c61f" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac750">
		<description>System Software 7.5</description>
		<year>1994</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac750" sha1="9b59a611f0fddd560bc8b72c1dae07d0f2e10dcc" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac753">
		<description>System Software 7.5.3 Revision 2</description>
		<year>1996</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac753" sha1="757e4c69281993871bb7a199583f8f0c042c0ac7" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac755">
		<description>System Software 7.5.5</description>
		<year>1996</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac755" sha1="45990ff07419555d576eaa4f2293d62e74d055b6" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac760">
		<description>System Software 7.6</description>
		<year>1997</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac760" sha1="7e5ac00619dbf2395611f19658fab8e029d64bc7" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac761">
		<description>System Software 7.6.1</description>
		<year>1997</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac761" sha1="fa41734a26c37dea26f5d5590a8545afe26005ac" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac80">
		<description>Mac OS 8.0 (US English)</description>
		<year>1997</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac80" sha1="d1bcb1f3fc8bff56f95fc09e19a615d9d192ed4c" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac81">
		<description>Mac OS 8.1 (US English)</description>
		<year>1998</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac81" sha1="e9bedc463266fff9b5fb2121448be8adafebe2ae" writeable="yes"/>
			</diskarea>
		</part>
	</software>
</softwarelist>

=== mamedev/mame/hash/mtu130_flop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

Floppies for the MTU-130.
-->
<softwarelist name="mtu130_flop" description="MTU-130 floppies">

	<software name="demo">
		<description>Demonstration disk</description>
		<year>1982</year>
		<publisher>Micro Technology Unlimited</publisher>
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="408600">
				<rom name="Demonstration_Disk_1.5_1982_-_MTU-BASIC_Included.imd" size="408600" crc="55405b0a" sha1="a209f7cc77abf77d5fb1ecc6b36efd36dbc8b5fc"/>
			</dataarea>
		</part>
	</software>

	<software name="codos">
		<description>CODOS 2.0</description>
		<year>1982</year>
		<publisher>Micro Technology Unlimited</publisher>
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="245655">
				<rom name="Distribution_Disk_1.5_1982_-_CODOS_2.0.imd" size="245655" crc="5b628dce" sha1="d5d0a4a869c943f88d4f765a62e59e069f5dd8f2"/>
			</dataarea>
		</part>
	</software>

	<software name="basic10">
		<description>BASIC 1.0 and extra libs</description>
		<year>1982</year>
		<publisher>Micro Technology Unlimited</publisher>
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="501930">
				<rom name="Distribution_Disk_1.4_1982_-_BASIC_IGL_CIL_VGL_KGL_and_Diskex.imd" size="501930" crc="3b747614" sha1="b2a25bcc05cc789b7a506d1860815cf80ff1984e"/>
			</dataarea>
		</part>
	</software>

	<software name="basic15">
		<description>BASIC 1.5</description>
		<year>1982</year>
		<publisher>Micro Technology Unlimited</publisher>
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="499125">
				<rom name="Distribution_Disk_1.4_1982_-_CODOS_2.0__BASIC_1.5.imd" size="499125" crc="750d7783" sha1="d91f4d223774b76657b6df6cb026a56a0dc693d2"/>
			</dataarea>
		</part>
	</software>

	<software name="datamover">
		<description>Datamover support disk</description>
		<year>?</year>
		<publisher>Micro Technology Unlimited</publisher>
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="223215">
				<rom name="Distribution_Disk_1.7_-_MTU-140_Datamover.imd" size="223215" crc="81171694" sha1="919f32a3113090a2c8e6da6d8b44b51c6f8afa1a"/>
			</dataarea>
		</part>
	</software>

	<software name="multio">
		<description>MultI-O support disk</description>
		<year>1983</year>
		<publisher>Micro Technology Unlimited</publisher>
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="358875">
				<rom name="Distribution_Disk_1.1_-_1983_MULTI-O.imd" size="358875" crc="d506fd60" sha1="bea333b342ec97dca45fcd60b7bb0da7113b3703"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/hp9825_rom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

HP9825A/B/T option ROMs
Compiled by F.Ulivi with data from http://www.hpmuseum.net/
-->

<softwarelist name="hp9825_rom" description="HP 9825 Option ROMs">
	<software name="string_advprg">
		<description>String/Advanced programming ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98210A" />
		<sharedfeat name="compatibility" value="A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom4000" size="0x800" width="16" endianness="big">
				<rom name="advanced.bin" size="0x800" crc="965b5e5a" sha1="ff44dd15f8fa4ca03dfd970ed8b200e8a071ec13" />
			</dataarea>
			<dataarea name="rom4c00" size="0x800" width="16" endianness="big">
				<rom name="strings.bin" size="0x800" crc="b5ca5da5" sha1="af13abb3c15836c566863c656e1659f7e6f96d04" />
			</dataarea>
		</part>
	</software>

	<software name="matrix">
		<description>Matrix ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98211A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3c00" size="0x800" width="16" endianness="big">
				<rom name="98211a.bin" size="0x800" crc="2cec553f" sha1="95c8d8becae6948accb342d23bc7072f0adb2c67" />
			</dataarea>
		</part>
	</software>

	<software name="plot9862_genio">
		<description>9862 Plotter/Gen I/O ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98212A" />
		<sharedfeat name="compatibility" value="A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3400" size="0x800" width="16" endianness="big">
				<rom name="general_io.bin" size="0x800" crc="b0386cb6" sha1="1b3a54edf54a5bdf92d1f7c6ec332fc00b037b49" />
			</dataarea>
			<dataarea name="rom3800" size="0x800" width="16" endianness="big">
				<rom name="plot9862.bin" size="0x800" crc="89db2f9c" sha1="6fff6637a450d230e6d9716d88cb54e592157416" />
			</dataarea>
		</part>
	</software>

	<software name="genio_ext">
		<description>General/extended I/O ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98213A"  />
		<sharedfeat name="compatibility" value="A"/>
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3400" size="0x800" width="16" endianness="big">
				<rom name="general_io.bin" size="0x800" crc="b0386cb6" sha1="1b3a54edf54a5bdf92d1f7c6ec332fc00b037b49"/>
			</dataarea>
			<dataarea name="rom4400" size="0x1000" width="16" endianness="big">
				<rom name="extended_io.bin" size="0x1000" crc="1d67b773" sha1="4031bb00e49f7ea462aa6468f7e77b8589879a6a"/>
			</dataarea>
		</part>
	</software>

	<software name="genio_ext_plot62">
		<description>General/extended I/O/9862 plotter ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98214A" />
		<sharedfeat name="compatibility" value="A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3400" size="0x800" width="16" endianness="big">
				<rom name="general_io.bin" size="0x800" crc="b0386cb6" sha1="1b3a54edf54a5bdf92d1f7c6ec332fc00b037b49" />
			</dataarea>
			<dataarea name="rom3800" size="0x800" width="16" endianness="big">
				<rom name="plot9862.bin" size="0x800" crc="89db2f9c" sha1="6fff6637a450d230e6d9716d88cb54e592157416" />
			</dataarea>
			<dataarea name="rom4400" size="0x1000" width="16" endianness="big">
				<rom name="extended_io.bin" size="0x1000" crc="1d67b773" sha1="4031bb00e49f7ea462aa6468f7e77b8589879a6a" />
			</dataarea>
		</part>
	</software>

	<software name="plot_genio">
		<description>Plotter/Gen I/O ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98215A" />
		<sharedfeat name="compatibility" value="A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3400" size="0x800" width="16" endianness="big">
				<rom name="general_io.bin" size="0x800" crc="b0386cb6" sha1="1b3a54edf54a5bdf92d1f7c6ec332fc00b037b49" />
			</dataarea>
			<dataarea name="rom3800" size="0x800" width="16" endianness="big">
				<rom name="plot9872.bin" size="0x800" crc="0a9cb8db" sha1="d0d126fca108f2715e1e408cb31b09ba69385ac4" />
			</dataarea>
		</part>
	</software>

	<software name="genio_ext_plot">
		<description>General/extended I/O/plotter ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98216A" />
		<sharedfeat name="compatibility" value="A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3400" size="0x800" width="16" endianness="big">
				<rom name="general_io.bin" size="0x800" crc="b0386cb6" sha1="1b3a54edf54a5bdf92d1f7c6ec332fc00b037b49" />
			</dataarea>
			<dataarea name="rom3800" size="0x800" width="16" endianness="big">
				<rom name="plot9872.bin" size="0x800" crc="0a9cb8db" sha1="d0d126fca108f2715e1e408cb31b09ba69385ac4" />
			</dataarea>
			<dataarea name="rom4400" size="0x1000" width="16" endianness="big">
				<rom name="extended_io.bin" size="0x1000" crc="1d67b773" sha1="4031bb00e49f7ea462aa6468f7e77b8589879a6a" />
			</dataarea>
		</part>
	</software>

	<software name="mass">
		<description>9885 ROM for 9825</description>
		<year>1976</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98217A" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom3000" size="0x800" width="16" endianness="big">
				<rom name="98217a.bin" size="0x800" crc="ee41c924" sha1="eac268523c09291a9939bc2dac201e4285185b51" />
			</dataarea>
		</part>
	</software>

	<software name="mass2">
		<description>9885/9895 ROM for 9825</description>
		<year>1980</year>
		<publisher>Hewlett-Packard</publisher>
		<info name="serial" value="98228A" />
		<sharedfeat name="compatibility" value="T" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom5c00" size="0x4000" width="16" endianness="big">
				<rom name="98228a.bin" size="0x4000" crc="31ce695e" sha1="b61273356c421102ff2bbd6aa7277200ee778097" />
			</dataarea>
		</part>
	</software>

	<software name="sssmass">
		<description>SSS mass storage ROM</description>
		<year>1984</year>
		<publisher>Structured Software Systems</publisher>
		<sharedfeat name="compatibility" value="T" />
		<part name="rom" interface="hp9825_rom">
			<dataarea name="rom5c00" size="0x4000" width="16" endianness="big">
				<rom name="sssmass.bin" size="0x4000" crc="95d36297" sha1="5e1777c894f6507a461c4a12f12ae5ac2c7a4385" />
			</dataarea>
		</part>
	</software>
</softwarelist>
