=== mamedev/mame/trunk/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT software (description, year?, publisher, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea databits (8|16|32|64) "8">
				<!ATTLIST dataarea endian (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== mamedev/mame/hash/bbc_hdd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="bbc_hdd" description="Acorn BBC Micro hard disks">

	<software name="cf_v103">
		<description>Master 128 ADFS Hard Drive Image V1.03</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="M" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_v103" sha1="380b817645fcbea317973db59f10db5120e8ac44" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_v105">
		<description>Master 128 ADFS Hard Drive Image V1.05</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="M" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_v105" sha1="9980aee632803ae4986b7ef56e2020a09ddde2b6" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_b106e">
		<description>Model B ADFS Hard Drive Image B1.06e</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_b106en" sha1="f7cb1132c78a1c742661a0bf6366dc7e8139fe96" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_t107">
		<description>Model B ADFS Hard Drive Image T1.07</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_t107" sha1="b6daa6b1973e762ed61b153845a8dfb26d7b0271" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_b131r">
		<description>Model B ADFS Hard Drive Image B1.31 (Retro Software)</description>
		<year>2010</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf_b131r" sha1="b921e3d5d5d359af7be6626fd928754ecf19a7ff" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_b142">
		<description>Model B ADFS Hard Drive Image B1.42</description>
		<year>2010</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf_b142" sha1="1f155b6bf1730c070314adf7387baf891476a668" writeable="yes" />
			</diskarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/aim65_cart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="aim65_cart" description="Rockwell AIM 65 cartridges">

<!--

  There are 5 ROM sockets on the AIM 65 PCB: 2 sockets were for the boot strap and 3 sockets for software roms,
  at locations z24, z25, and z26. A PROM/ROM module can be added to provide additional sockets at z12, z13, z14,
  and z15.

-->

	<software name="assemblr">
		<description>AIM 65 Assembler</description>
		<year>1979</year>
		<publisher>Rockwell</publisher>
		<info name="usage" value="Load in &quot;cart3&quot;, then press N to start"/>

		<part name="z24" interface="aim65_z24_cart">
			<dataarea name="z24" size="4096">
				<rom name="assembler.z24" size="4096" crc="0878b399" sha1="483e92b57d64be51643a9f6490521a8572aa2f68"/>
			</dataarea>
		</part>
	</software>

	<software name="basic11">
		<description>AIM 65 BASIC v1.1</description>
		<year>1978</year>
		<publisher>Rockwell/Microsoft</publisher>
		<info name="usage" value="Load in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="basic.z26" size="4096" crc="36a61f39" sha1="f5ce0126cb594a565e730973fd140d03c298cefa"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="basic.z25" size="4096" crc="d7b42d2a" sha1="4bbdb28d332429825adea0266ed9192786d9e392"/>
			</dataarea>
		</part>
	</software>

	<!-- Found on a Comelta DRAC-1 machine. -->
	<software name="basic11a" cloneof="basic11">
		<description>AIM 65 BASIC v1.1 (alt)</description>
		<year>1978</year>
		<publisher>Rockwell/Microsoft</publisher>
		<info name="usage" value="Load in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="r3226.z26" size="4096" crc="36a61f39" sha1="f5ce0126cb594a565e730973fd140d03c298cefa"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="r3225.z25" size="4096" crc="d7b42d2a" sha1="4bbdb28d332429825adea0266ed9192786d9e392"/>
			</dataarea>
		</part>
		<part name="z24" interface="aim65_z24_cart">
			<dataarea name="z24" size="4096">
				<rom name="crosaim_v1.3_b_asse-1_d000.z24" size="4096" crc="b7472a5e" sha1="333630bafa93e7236e3c7a8d14f16f2ba551fd26"/>
			</dataarea>
		</part>
	</software>

	<software name="extbas21">
		<description>AIM 65/PC100 Extended BASIC v2.1</description>
		<year>1980</year>
		<publisher>GWK</publisher>
		<info name="usage" value="Load in &quot;cart1&quot;, &quot;cart2&quot; and &quot;cart3&quot;, then press N to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="gwk extended basic v2.1.z26" size="4096" crc="3ec90376" sha1="22322cfc490615c58a6260a43138e5b47ecb10a1"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="gwk extended basic v2.1.z25" size="4096" crc="ac50cedb" sha1="848887fe5c6a6c0c2d9f7c082f531bc9ebd60e51"/>
			</dataarea>
		</part>
		<part name="z24" interface="aim65_z24_cart">
			<dataarea name="z24" size="4096">
				<rom name="gwk extended basic v2.1.z24" size="4096" crc="5bb93856" sha1="7684a1e7c1b566ca5c93c73d1e4e0e8eaa4400ad"/>
			</dataarea>
		</part>
	</software>

	<software name="extbas23">
		<description>AIM 65/PC100 Extended BASIC v2.3</description>
		<year>1980</year>
		<publisher>GWK</publisher>
		<info name="usage" value="Load in &quot;cart1&quot;, &quot;cart2&quot; and &quot;cart3&quot;, then press N to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="gwk extended basic v2.3.z26" size="4096" crc="841b05fa" sha1="f930bd8db542fe1edc37abda4cddaec6bcd093e2"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="gwk extended basic v2.3.z25" size="4096" crc="31de604c" sha1="0b80c5015c125acd75a3883f924e48fd928bdff7"/>
			</dataarea>
		</part>
		<part name="z24" interface="aim65_z24_cart">
			<dataarea name="z24" size="4096">
				<rom name="gwk extended basic v2.3.z24" size="4096" crc="5aa4e61e" sha1="62dbff204b6cccbe3dc8fc5298260c0dfdb9a632"/>
			</dataarea>
		</part>
	</software>

	<software name="basicpc100">
		<description>Siemens PC100 BASIC</description>
		<year>1978</year>
		<publisher>Siemens/Microsoft</publisher>
		<info name="usage" value="Load in &quot;cart1&quot;, &quot;cart2&quot; and &quot;cart3&quot;, then press N to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="pc100_basic.z26" size="4096" crc="36a61f39" sha1="f5ce0126cb594a565e730973fd140d03c298cefa"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="pc100_basic.z25" size="4096" crc="00326f73" sha1="b84922f459482ddfc9a412998a4fb9048719c412"/>
			</dataarea>
		</part>
		<part name="z24" interface="aim65_z24_cart">
			<dataarea name="z24" size="4096">
				<rom name="pc100_basic.z24" size="4096" crc="0878b399" sha1="483e92b57d64be51643a9f6490521a8572aa2f68"/>
			</dataarea>
		</part>
	</software>

	<software name="forth13">
		<description>AIM 65 FORTH v1.3</description>
		<year>1981</year>
		<publisher>Rockwell</publisher>
		<info name="usage" value="Load in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="forth v1.3.z26" size="4096" crc="a80ad472" sha1="42a2e8c86829a2fe48090e6665ff9fe25b12b070"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="forth v1.3.z25" size="4096" crc="0671d019" sha1="dd2a1613e435c833634100cf4a22c6cff70c7a26"/>
			</dataarea>
		</part>
	</software>

	<software name="mathpack" cloneof="forth13">
		<description>AIM 65 FORTH v1.3 w/ Mathpack</description>
		<year>198?</year>
		<publisher>Rockwell</publisher>
		<info name="usage" value="Load in &quot;cart1&quot;, &quot;cart2&quot; and &quot;cart3&quot;, then press N to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="forth v1.3.z26" size="4096" crc="a80ad472" sha1="42a2e8c86829a2fe48090e6665ff9fe25b12b070"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="forth v1.3.z25" size="4096" crc="0671d019" sha1="dd2a1613e435c833634100cf4a22c6cff70c7a26"/>
			</dataarea>
		</part>
		<part name="z24" interface="aim65_z24_cart">
			<dataarea name="z24" size="4096">
				<rom name="mathpack.z24" size="4096" crc="4889af55" sha1="5e9541ddfc06e3802d09b30d1bd89c5da914c76e"/>
			</dataarea>
		</part>
	</software>

	<software name="pascal10">
		<description>AIM 65 Instant Pascal v1.0</description>
		<year>1981</year>
		<publisher>Rockwell</publisher>
		<info name="usage" value="Load in &quot;cart1&quot; &quot;cart4&quot; &quot;cart5&quot; &quot;cart6&quot; and &quot;cart7&quot;, then press 5 to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="r32p6.z26" size="4096" crc="ae41b361" sha1="fd4c28675920d464ca3e97578c2fd9536299bf44"/>
			</dataarea>
		</part>
		<part name="z12" interface="rm65_z12_cart">
			<dataarea name="z12" size="4096">
				<rom name="r32p2.z12" size="4096" crc="e83786c7" sha1="a0c08648af48d766e53b04cc04bbfa3502b85beb"/>
			</dataarea>
		</part>
		<part name="z13" interface="rm65_z13_cart">
			<dataarea name="z13" size="4096">
				<rom name="r32p3.z13" size="4096" crc="32d6e231" sha1="fd9e549d8c3e14ec1ba22e87260b65d38f9a3be5"/>
			</dataarea>
		</part>
		<part name="z14" interface="rm65_z14_cart">
			<dataarea name="z14" size="4096">
				<rom name="r32p4.z14" size="4096" crc="a703a2c3" sha1="9b5737625a54b041dfd432fff3dafef6e80ce640"/>
			</dataarea>
		</part>
		<part name="z15" interface="rm65_z15_cart">
			<dataarea name="z15" size="4096">
				<rom name="r32p5.z15" size="4096" crc="05bd6507" sha1="68fd30893e05d1ea7f0a0cf497470506e8b94cbe"/>
			</dataarea>
		</part>
	</software>

	<software name="pl65">
		<description>AIM 65 PL/65 v1.0</description>
		<year>1980</year>
		<publisher>Rockwell</publisher>
		<info name="usage" value="Load in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="z26" interface="aim65_z26_cart">
			<dataarea name="z26" size="4096">
				<rom name="pl65 v1.0.z26" size="4096" crc="2ac71abd" sha1="6df5e3125bebefac80d51d9337555f54bdf0d8ea"/>
			</dataarea>
		</part>
		<part name="z25" interface="aim65_z25_cart">
			<dataarea name="z25" size="4096">
				<rom name="pl65 v1.0.z25" size="4096" crc="76dcf864" sha1="e937c54ed109401f796640cd45b27dfefb76667e"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/tiki100_hdd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="tiki100_hdd" description="TIKI-100 hard disks">

	<software name="tiko401">
		<description>TIKO v4.01 Winchester system (Norway)</description>
		<year>198?</year>
		<publisher>Tiki Data</publisher>

		<part name="hdd" interface="tiki100_hdd">
			<diskarea name="harddriv">
				<disk name="tiko401" sha1="8e98634337f1a71259dbf80aac976e53eb91ec68" writeable="yes" />
			</diskarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/sd132_flop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="sd132_flop" description="Ensoniq SD-1 32 Voice disk images">

	<software name="os400" cloneof="os410" supported="yes">
		<description>SD-1 Sequencer OS version 4.00</description>
		<year>1991</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SD1_OS_4_00.img" size="819200" crc="e218f989" sha1="6ba14f4ff2ad99800478893716d9c14a61a7eb38" />
			</dataarea>
		</part>
	</software>

	<software name="os410" supported="yes">
		<description>SD-1 Sequencer OS version 4.10</description>
		<year>1992</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SD1_OS_4_10.img" size="819200" crc="82fb69a4" sha1="152a1147ccb0424a9e8d96ca948c085fadcaf361" />
			</dataarea>
		</part>
	</software>

	<software name="sd1_32_demo1" supported="yes">
		<description>SD-1 32 Voice Demo Disk #1</description>
		<year>1992</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SD1_32Voice_DemoDisk1.img" size="819200" crc="7cfb73c5" sha1="0e5f8a3b64674d56d40346e62f7a095ace83bb55" />
			</dataarea>
		</part>
	</software>

	<software name="multi_demo1" supported="yes">
		<description>Multi-Product Demo Disk #1</description>
		<year>1992</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="MultiProductDemoDisk1.img" size="819200" crc="2a5456a1" sha1="c9ab9199fac474c01751ba0d1678dcd72ff57834" />
			</dataarea>
		</part>
	</software>

	<software name="multi_demo2" supported="yes">
		<description>Multi-Product Demo Disk #2</description>
		<year>1993</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="MultiProductDemoDisk2.img" size="819200" crc="4f017eaf" sha1="65f3734cfab0fd79ec192674383be7b76e45d5b3" />
			</dataarea>
		</part>
	</software>

	<software name="sq32_demo1" supported="yes">
		<description>SQ 32 Voice Demo Disk #2</description>
		<year>1993</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SQ_32Voice_DemoDisk1.img" size="819200" crc="91ba0cc0" sha1="c7e3f803122ce9b8b860724a064c40bd9747da41" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/cbcomm.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="cbcomm" description="VTech / EG Computer Bit Communicator cartridges">

<!--

Some carts only contain a jumper, probably pointing to code already in the main unit ROM.
Other carts have ROM and RAM.

The following cartridges have been verified to only contain a jumper:

+- - - - - - - - +- - - - - - - - - - - - - - - +- - - - - - - - -
|   CART CODE    |          CART NAME           |  JUMPER STATUS  |
+- - - - - - - - +- - - - - - - - - - - - - - - +- - - - - - - - -
|                |                              |                 |
| 80-9755-2      | Black & White                | all 3 down      |
| 80-9755-2      | Rally                        | central up      |

The following cartridges have been verified to contain ROM and RAM:

+- - - - - - - - - - - - +- - - - - - - - - - - - - - -+- - - - - - +- - - - - - - - +- - - - - - - - -
|   CART CODE            |          CART NAME          |  EPROM-ID  |  EPROM-TYPE    |    RAM-TYPE     |
+- - - - - - - - - - - - +- - - - - - - - - - - - - - -+- - - - - - +- - - - - - - - +- - - - - - - - -
|                        |                             |            |                |                 |
| 35-28000-019 704074-1  | e.mail                      | 27-6445-24 |   LH5V2GT6     | GM76FV18ALLFW70 |

-->

	<software name="email" supported="no">
		<description>e.mail</description>
		<year>2000?</year>
		<publisher>Video Technology / EG</publisher>
		<part name="rom" interface="genius_rom">
			<dataarea name="rom" size="0x40000">
				<rom name="27-6445-24.h2" size="0x40000" crc="53ebfd8b" sha1="1a4d1d55851d5b3434d35e4d53b481b0ca08fd59"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/k28.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<!--

Known modules:

1st series:
- Spelling I: VSM: 16KB CM62086
- Spelling II: VSM: 16KB CM6????
- Spelling III: VSM: 16KB CM62087
- other: ?

2nd series:
- Spelling 1 (Expansion Module 1): VSM: 16KB CM62214
- Spelling 2 (Expansion Module 2): VSM: 16KB CM62216
- Spelling 3 (Expansion Module 3): VSM: 16KB CM62215
- Spelling 4 (Expansion Module 4): VSM: 16KB CM62217
- Sentence Superstars (Expansion Module 5): VSM: 16KB CM6????
- Vowel Detectives (Expansion Module 6): VSM: 16KB CM62219

For the 2nd series, the first 4 are (C) Tiger Electronics, modules 5 and 6 are
(C) Coleco Industries. The cartridge labels don't show the title, but simply say
"Expansion Module x" where x = 1-6.

It is assumed that the 1st series Spelling modules are the same as the Expansion
modules. CM62215 and CM62087 were confirmed same, CM62214 and CM62086 too.

Spelling 2 and Spelling 3 are indeed CM62216 and CM62215, this swapped ordering
is not an error.

-->

<softwarelist name="k28" description="K-2-8 (model 7-232) modules">

	<software name="spell1">
		<description>Spelling 1 (Expansion Module 1)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8111"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62214" size="0x4000" crc="0349798b" sha1="afdad242f9c7dec0c5fd83670e3d8f1637140e76" />
			</dataarea>
		</part>
	</software>

	<software name="spell2">
		<description>Spelling 2 (Expansion Module 2)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8112"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62216" size="0x4000" crc="1c99306f" sha1="7bfadeec79bdc231c4e3447149e2f6542cfe077d" />
			</dataarea>
		</part>
	</software>

	<software name="spell3">
		<description>Spelling 3 (Expansion Module 3)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8113"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62215" size="0x4000" crc="f2deb9a2" sha1="9fb264b869d1298ebd76811931bed83ac122fe4b" />
			</dataarea>
		</part>
	</software>

	<software name="spell4">
		<description>Spelling 4 (Expansion Module 4)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8114"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62217" size="0x4000" crc="995936b2" sha1="8bd0fea4ade9972d1d6cb521f9367c971c7eead6" />
			</dataarea>
		</part>
	</software>

	<software name="vdetect">
		<description>Vowel Detectives (Expansion Module 6)</description>
		<year>1987</year>
		<publisher>Coleco</publisher>
		<info name="serial" value="8116"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62219" size="0x4000" crc="177b5cb5" sha1="2ed44fea8f931fc8aa46dafdda1c6c30b8c9dc01" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/super6.xml
<?xml version="1.0"?>
<!--
license:CC0-1.0
-->
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="super6" description="ADC Super Six diskettes">

	<software name="cpm22">
		<description>CP/M 2.2</description>
		<year>198?</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="175545">
				<rom name="cpm22.imd" size="175545" crc="86aea137" sha1="61fdfaaedaf5f4945f51cfd7550efc3957860316"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_8">
			<dataarea name="flop" size="242555">
				<rom name="cpm22r.imd" size="242555" crc="6df9024e" sha1="9bed3f5742fb712a1af53a4b9bb10f7f9a5873b4"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_8">
			<dataarea name="flop" size="206359">
				<rom name="sbios256.imd" size="206359" crc="cef80a0c" sha1="9184c84a5d540f7d4a8a7fe4ef0b6c913e0af542"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_8">
			<dataarea name="flop" size="451102">
				<rom name="sbios_23.imd" size="451102" crc="eb4cdd6d" sha1="64585b03ea5a154caee00de08ef09dbd02415d9c"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_8">
			<dataarea name="flop" size="527061">
				<rom name="sbios_s6.imd" size="527061" crc="891cd9a9" sha1="cd9cfea2e1178084fd4c85fb873dedfbb4f41706"/>
			</dataarea>
		</part>
	</software>

	<software name="digi56" supported="no">
		<description>digi56</description>
		<year>198?</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop" interface="floppy_8">
			<dataarea name="flop" size="472732">
				<rom name="digi56.imd" size="472732" crc="b31a174c" sha1="7e7e99e24032d96c5823c1345c55101cf1d2ca2c"/>
			</dataarea>
		</part>
	</software>

	<software name="tdos122p" supported="no">
		<description>TurboDOS v1.22p</description>
		<year>198?</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop1" interface="floppy_8">
			<feature name="part_id" value="Operating system disk"/>
			<dataarea name="flop" size="205576">
				<rom name="12_1.imd" size="205576" crc="50ba328b" sha1="c40427b7286f8faec207e2a403c6a02e6172636d"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_8">
			<feature name="part_id" value="Bootable disk"/>
			<dataarea name="flop" size="197706">
				<rom name="12_2.imd" size="197706" crc="88811af4" sha1="374b8e3b6463e19817fd55c2b57329487265fc85"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_8">
			<feature name="part_id" value="Disk drivers disk"/>
			<dataarea name="flop" size="228565">
				<rom name="12_3.imd" size="228565" crc="928904ca" sha1="04667695851e30b89293a15fea702c1ab714fd33"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_8">
			<feature name="part_id" value="Non-disk drivers disk"/>
			<dataarea name="flop" size="168239">
				<rom name="12_4.imd" size="168239" crc="917266c3" sha1="ec69d986abff8bf72289df3ad5e189a31715edb5"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_8">
			<feature name="part_id" value="GEN, PAR and DOC files"/>
			<dataarea name="flop" size="180559">
				<rom name="12_5.imd" size="180559" crc="dcb7a3d5" sha1="7a0935bc8d18d7345eae52b055ed2cfd4137f7b5"/>
			</dataarea>
		</part>
	</software>

	<software name="tdos14" supported="no">
		<description>TurboDOS v1.4</description>
		<year>1985</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop1" interface="floppy_8">
			<feature name="part_id" value="Primary"/>
			<dataarea name="flop" size="1033649">
				<rom name="14_1.imd" size="1033649" crc="082d934c" sha1="eb8ded42f87acb943ca970d692bc963f259c0be1"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_8">
			<feature name="part_id" value="GEN, PAR and DOC files"/>
			<dataarea name="flop" size="220201">
				<rom name="14_2.imd" size="220201" crc="3beb825f" sha1="70d6cefaae69bab3ef96ca84e662fdc81b2c7e6c"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_8">
			<feature name="part_id" value="Disk drivers disk"/>
			<dataarea name="flop" size="351139">
				<rom name="14_3.imd" size="351139" crc="cd7f9d60" sha1="07b2d33ceb2241c8d045120a50a77d18281d9797"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_8">
			<feature name="part_id" value="DPROG"/>
			<dataarea name="flop" size="407719">
				<rom name="14_4.imd" size="407719" crc="61bf5d11" sha1="2307ebd1ea7783780966aefde56c361e708ba549"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_8">
			<feature name="part_id" value="Backup"/>
			<dataarea name="flop" size="896541">
				<rom name="14_5.imd" size="896541" crc="1e1f7818" sha1="0f3a2f2ac6fd77e6e9ccf14a990e8e4f7dc527e1"/>
			</dataarea>
		</part>
		<part name="flop6" interface="floppy_8">
			<feature name="part_id" value="System disk"/>
			<dataarea name="flop" size="217116">
				<rom name="14_6.imd" size="217116" crc="aff49cce" sha1="f4bc3ba45a522082058bdc209d61c33fcd8466d3"/>
			</dataarea>
		</part>
		<part name="flop7" interface="floppy_8">
			<feature name="part_id" value="Generation disk"/>
			<dataarea name="flop" size="396137">
				<rom name="14_7.imd" size="396137" crc="5a81c9ce" sha1="e89281786973fd778656bfc72a4a4e174ea9efcd"/>
			</dataarea>
		</part>
		<part name="flop8" interface="floppy_8">
			<feature name="part_id" value="Deltasoft Multi User BASIC"/>
			<dataarea name="flop" size="152879">
				<rom name="14_8.imd" size="152879" crc="28e55937" sha1="23e1999e5a71ee36e04e142e28414d20182f6401"/>
			</dataarea>
		</part>
		<part name="flop9" interface="floppy_8">
			<dataarea name="flop" size="354469">
				<rom name="bios.imd" size="354469" crc="98188a65" sha1="5ab78191022cdfaf4aa28319770e7ab6e91eb737"/>
			</dataarea>
		</part>
		<part name="flop10" interface="floppy_8">
			<feature name="part_id" value="COM files, TurboSlave PAR+GEN files, boot tracks on disk"/>
			<dataarea name="flop" size="1036746">
				<rom name="slave.imd" size="1036746" crc="1602ab7c" sha1="5f75c227fb3b9a3838d0a60efab8c1b162638652"/>
			</dataarea>
		</part>
	</software>

</softwarelist>
